<a href="https://colab.research.google.com/github/Elensk8/Anal-tica_Neg/blob/main/ProyectoFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Base de datos Churn (Banco)**

# **Equipo: Juan Carlos Cifuentes, Elena Restrepo y Juan Jose Puerta.**

**Implementamos el modelo de pronóstico de Redes Neuronales**

0. Cargar las librerías de trabajo

In [42]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

1. Instalamos los paquetes de trabajo

In [41]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.4)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.13.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.71.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.8.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.13.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.0.9)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.4.26)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.8)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

2. Cargar la base de datos y las variables que vamos a utilizar

In [93]:
nxl = '/content/Churn_Modelling.csv'
XDB = pd.read_csv(nxl)  # Usa read_csv si el archivo es .csv

# Selección de variables
XDB = XDB[['CustomerId', 'CreditScore', 'Age', 'Balance',
           'NumOfProducts', 'HasCrCard', 'IsActiveMember',
           'EstimatedSalary', 'Exited']]

# Variables de entrada (X) y salida (y)
XD = np.array(XDB[['CustomerId', 'CreditScore', 'Age', 'Balance',
                   'NumOfProducts', 'HasCrCard', 'IsActiveMember',
                   'EstimatedSalary']])
XDn = XD / np.max(XD, axis=0)  # Normalización

yd = np.array(XDB['Exited'])  # Variable binaria (no se normaliza)

print("Los datos de entrada normalizados son:\n", XDn)

Los datos de entrada normalizados son:
 [[0.9885501  0.72823529 0.45652174 ... 1.         1.         0.50676345]
 [0.98935367 0.71529412 0.44565217 ... 0.         1.         0.56273406]
 [0.98758284 0.59058824 0.45652174 ... 1.         0.         0.56967927]
 ...
 [0.98538426 0.83411765 0.39130435 ... 0.         1.         0.21043581]
 [0.99156945 0.90823529 0.45652174 ... 1.         0.         0.46446006]
 [0.98815284 0.93176471 0.30434783 ... 1.         0.         0.19096108]]

##**MADALINE - MULTI ADALINE**
3. Se procede con el diseño del modelo MADALINE

**Con Softmax**

In [119]:
# Variables de entrada (X) y salida (y)
XD = np.array(XDB[[ 'CreditScore', 'Age', 'Balance',
                   'NumOfProducts', 'HasCrCard', 'IsActiveMember',
                   'EstimatedSalary']])
XDn = XD / np.max(XD, axis=0)  # Normalización

yd = np.array(XDB['Exited'])  # Variable binaria (no se normaliza)

# Normalize yd and assign to ydn. Using max as a scaling factor.
# Note: For binary classification with a neural network, using the raw 0/1 values
# and binary_crossentropy loss with a sigmoid output activation is more standard.
# However, based on the original code using 'mse' loss, scaling might be intended.
#ydn = yd / np.max(yd)
from tensorflow.keras.utils import to_categorical

ydn=to_categorical(yd)  #aseguro que la variable es categorica


print("Los datos de entrada normalizados son:\n", XDn)
print("Los datos de salida normalizados son:\n", ydn) # Add this print for verification

# ##**MADALINE - MULTI ADALINE**
# 7. Se procede con el diseño del modelo MADALINE
# %%
madaline=tf.keras.models.Sequential([
    tf.keras.layers.Dense(10,input_shape=(7,),activation='relu',use_bias=False), #Capa 1 _ 10 refresiones lineales
    tf.keras.layers.Dense(2,activation='softmax',use_bias=False)]) #Capa 2: Nucleo - Salida del modelo
madaline.compile(optimizer='adam',loss='categorical_crossentropy') #sgd: Solve Descend Gradient. mse= Mean Square Error -Quiero que sea cero.

history=madaline.fit(XDn,ydn,epochs=100) #Recorra la tabla de datos 100 veces
ydp=madaline.predict(XDn) #pronóstico al final del aprendizaje
ydp2 =ydp.argmax(axis=1)

from sklearn.metrics import classification_report, confusion_matrix
print("Matriz de confusión:")
print(confusion_matrix(yd, ydp2))

cm=np.array(confusion_matrix(yd,ydp2))

VN=cm[0,0]; FP=cm[0,1]; FN=cm[1,0]; VP=cm[1,1]
Ex=(VN+VP)/(VN+FP+FN+VP)
print("Exactitud: ",Ex)

TE=(FN+FP)/(VN+FP+FN+VP)
print("Tasa de error: ",TE)



df = pd.DataFrame(np.column_stack((ydn,ydp)))
print("La correlación de los datos es:\n",df.corr())

#Obtenemos las conexiones de la red - Como se dispersan las conexiones nerviosas
WC=madaline.get_weights() # Estas son las capas
# There are only two layers and no bias, so WC will have two elements
W=WC[0];C=WC[1] #Capa 0 - 4 a 10: Capa 1 - 10 a 1 Salida. Conexiones nerviosas (10 regresiones)
a=W@C #Producto entre las conexiones como Ws pasan entre los C
     #a: son los efectos indepencientes de las variables sobre la salida
    # Cual efecto es mas importantr que otro y cual tiene un efecto negativo o positivo sobre la salida.
df2=pd.DataFrame(a.T)
df2.columns=[[ 'CreditScore', 'Age', 'Balance',
                   'NumOfProducts', 'HasCrCard', 'IsActiveMember',
                   'EstimatedSalary']]
display(df2) #Muestra el peso que tiene cada variable  sobre la salida

Los datos de entrada normalizados son:
 [[0.72823529 0.45652174 0.         ... 1.         1.         0.50676345]
 [0.71529412 0.44565217 0.33403148 ... 0.         1.         0.56273406]
 [0.59058824 0.45652174 0.63635718 ... 1.         0.         0.56967927]
 ...
 [0.83411765 0.39130435 0.         ... 0.         1.         0.21043581]
 [0.90823529 0.45652174 0.29922631 ... 1.         0.         0.46446006]
 [0.93176471 0.30434783 0.51870777 ... 1.         0.         0.19096108]]
Los datos de salida normalizados son:
 [[0. 1.]
 [1. 0.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [1. 0.]]
Epoch 1/100

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6322
Epoch 2/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.4992
Epoch 3/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4880
Epoch 4/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4770
Epoch 5/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4714
Epoch 6/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4563
Epoch 7/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4681
Epoch 8/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4474
Epoch 9/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4453
Epoch 10/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4401
Epoch 11/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4314
Epoch 12/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4343
Epoch 13/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4332
Epoch 14/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4297
Epoch 15/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.4289
Epoch 16/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4239
Epoch 17/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4250
Epoch 18/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4229
Epoch 19/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4209
Epoch 20/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4215
Epoch 21/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4064
Epoch 22/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4094
Epoch 23/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4139
Epoch 24/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4105
Epoch 25/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4047
Epoch 26/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4087
Epoch 27/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4049
Epoch 28/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4021
Epoch 29/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4046
Epoch 30/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4069
Epoch 31/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4133
Epoch 32/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4094
Epoch 33/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4081
Epoch 34/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3934
Epoch 35/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3990
Epoch 36/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3969
Epoch 37/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3953
Epoch 38/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3945
Epoch 39/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4054
Epoch 40/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3925
Epoch 41/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3934
Epoch 42/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3976
Epoch 43/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3887
Epoch 44/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3901
Epoch 45/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3943
Epoch 46/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3927
Epoch 47/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3882
Epoch 48/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3877
Epoch 49/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3970
Epoch 50/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3908
Epoch 51/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3848
Epoch 52/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3985
Epoch 53/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3875
Epoch 54/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3862
Epoch 55/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3916
Epoch 56/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3874
Epoch 57/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3876
Epoch 58/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3878
Epoch 59/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3961
Epoch 60/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3777
Epoch 61/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3972
Epoch 62/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3857
Epoch 63/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3907
Epoch 64/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3892
Epoch 65/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3967
Epoch 66/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3837
Epoch 67/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3856
Epoch 68/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3916
Epoch 69/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3922
Epoch 70/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3801
Epoch 71/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3806
Epoch 72/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3925
Epoch 73/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3927
Epoch 74/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3813
Epoch 75/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3739
Epoch 76/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3860
Epoch 77/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3913
Epoch 78/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3849
Epoch 79/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3831
Epoch 80/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3813
Epoch 81/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3852
Epoch 82/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3877
Epoch 83/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3743
Epoch 84/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3842
Epoch 85/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3841
Epoch 86/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3878
Epoch 87/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3823
Epoch 88/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3885
Epoch 89/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3803
Epoch 90/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3722
Epoch 91/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3863
Epoch 92/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3814
Epoch 93/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3838
Epoch 94/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3832
Epoch 95/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3852
Epoch 96/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3958
Epoch 97/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3880
Epoch 98/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3806
Epoch 99/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3780
Epoch 100/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.3786
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
Matriz de confusión:
[[7714  249]
 [1318  719]]
Exactitud:  0.8433
Tasa de error:  0.1567
La correlación de los datos es:
           0         1         2         3
0  1.000000 -1.000000  0.520304 -0.520304
1 -1.000000  1.000000 -0.520304  0.520304
2  0.520304 -0.520304  1.000000 -1.000000
3 -0.520304  0.520304 -1.000000  1.000000

,CreditScore,Age,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,5.585486,1.539018,2.258316,-8.443069,-0.207749,-0.417367,0.085908
1,-6.385105,1.540881,-2.372226,5.572896,-0.379017,0.821612,-0.379007

**Con Sigmoid**

In [120]:
# Variables de entrada (X) y salida (y)
XD = np.array(XDB[[ 'CreditScore', 'Age', 'Balance',
                   'NumOfProducts', 'HasCrCard', 'IsActiveMember',
                   'EstimatedSalary']])
XDn = XD / np.max(XD, axis=0)  # Normalización

yd = np.array(XDB['Exited'])  # Variable binaria (no se normaliza)

# Normalize yd and assign to ydn. Using max as a scaling factor.
# Note: For binary classification with a neural network, using the raw 0/1 values
# and binary_crossentropy loss with a sigmoid output activation is more standard.
# However, based on the original code using 'mse' loss, scaling might be intended.
#ydn = yd / np.max(yd)
from tensorflow.keras.utils import to_categorical

ydn=to_categorical(yd)  #aseguro que la variable es categorica


print("Los datos de entrada normalizados son:\n", XDn)
print("Los datos de salida normalizados son:\n", ydn) # Add this print for verification

# ##**MADALINE - MULTI ADALINE**
# 7. Se procede con el diseño del modelo MADALINE
# %%
madaline=tf.keras.models.Sequential([
    tf.keras.layers.Dense(10,input_shape=(7,),activation='relu',use_bias=False), #Capa 1 _ 10 refresiones lineales
    tf.keras.layers.Dense(2,activation='sigmoid',use_bias=False)]) #Capa 2: Nucleo - Salida del modelo
madaline.compile(optimizer='adam',loss='categorical_crossentropy') #sgd: Solve Descend Gradient. mse= Mean Square Error -Quiero que sea cero.

history=madaline.fit(XDn,ydn,epochs=100) #Recorra la tabla de datos 100 veces
ydp=madaline.predict(XDn) #pronóstico al final del aprendizaje
ydp2 =ydp.argmax(axis=1)

from sklearn.metrics import classification_report, confusion_matrix
print("Matriz de confusión:")
print(confusion_matrix(yd, ydp2))

cm=np.array(confusion_matrix(yd,ydp2))

VN=cm[0,0]; FP=cm[0,1]; FN=cm[1,0]; VP=cm[1,1]
Ex=(VN+VP)/(VN+FP+FN+VP)
print("Exactitud: ",Ex)

TE=(FN+FP)/(VN+FP+FN+VP)
print("Tasa de error: ",TE)



df = pd.DataFrame(np.column_stack((ydn,ydp)))
print("La correlación de los datos es:\n",df.corr())

#Obtenemos las conexiones de la red - Como se dispersan las conexiones nerviosas
WC=madaline.get_weights() # Estas son las capas
# There are only two layers and no bias, so WC will have two elements
W=WC[0];C=WC[1] #Capa 0 - 4 a 10: Capa 1 - 10 a 1 Salida. Conexiones nerviosas (10 regresiones)
a=W@C #Producto entre las conexiones como Ws pasan entre los C
     #a: son los efectos indepencientes de las variables sobre la salida
    # Cual efecto es mas importantr que otro y cual tiene un efecto negativo o positivo sobre la salida.
df2=pd.DataFrame(a.T)
df2.columns=[[ 'CreditScore', 'Age', 'Balance',
                   'NumOfProducts', 'HasCrCard', 'IsActiveMember',
                   'EstimatedSalary']]
display(df2) #Muestra el peso que tiene cada variable  sobre la salida

Los datos de entrada normalizados son:
 [[0.72823529 0.45652174 0.         ... 1.         1.         0.50676345]
 [0.71529412 0.44565217 0.33403148 ... 0.         1.         0.56273406]
 [0.59058824 0.45652174 0.63635718 ... 1.         0.         0.56967927]
 ...
 [0.83411765 0.39130435 0.         ... 0.         1.         0.21043581]
 [0.90823529 0.45652174 0.29922631 ... 1.         0.         0.46446006]
 [0.93176471 0.30434783 0.51870777 ... 1.         0.         0.19096108]]
Los datos de salida normalizados son:
 [[0. 1.]
 [1. 0.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [1. 0.]]

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.6133
Epoch 2/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5169
Epoch 3/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.4935
Epoch 4/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4908
Epoch 5/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4771
Epoch 6/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4674
Epoch 7/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.4715
Epoch 8/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4645
Epoch 9/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.4455
Epoch 10/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4560
Epoch 11/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4427
Epoch 12/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4454
Epoch 13/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4367
Epoch 14/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4426
Epoch 15/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4393
Epoch 16/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4311
Epoch 17/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4257
Epoch 18/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4343
Epoch 19/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4420
Epoch 20/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4275
Epoch 21/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4246
Epoch 22/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4346
Epoch 23/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4218
Epoch 24/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4195
Epoch 25/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4204
Epoch 26/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4172
Epoch 27/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4110
Epoch 28/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4085
Epoch 29/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4097
Epoch 30/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4045
Epoch 31/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4098
Epoch 32/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4097
Epoch 33/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3994
Epoch 34/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4010
Epoch 35/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4077
Epoch 36/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3952
Epoch 37/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3964
Epoch 38/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3977
Epoch 39/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3948
Epoch 40/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3974
Epoch 41/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3979
Epoch 42/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3862
Epoch 43/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3973
Epoch 44/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3888
Epoch 45/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3980
Epoch 46/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3922
Epoch 47/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3940
Epoch 48/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3943
Epoch 49/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3926
Epoch 50/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3920
Epoch 51/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3925
Epoch 52/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3961
Epoch 53/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3896
Epoch 54/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3962
Epoch 55/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3866
Epoch 56/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3817
Epoch 57/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3948
Epoch 58/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3986
Epoch 59/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3869
Epoch 60/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3885
Epoch 61/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3907
Epoch 62/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3983
Epoch 63/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3934
Epoch 64/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3897
Epoch 65/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3804
Epoch 66/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3801
Epoch 67/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3868
Epoch 68/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3792
Epoch 69/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3833
Epoch 70/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3898
Epoch 71/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3820
Epoch 72/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3907
Epoch 73/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3866
Epoch 74/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3959
Epoch 75/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3834
Epoch 76/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3889
Epoch 77/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3903
Epoch 78/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3900
Epoch 79/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3913
Epoch 80/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3764
Epoch 81/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3819
Epoch 82/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3812
Epoch 83/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3925
Epoch 84/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3841
Epoch 85/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3733
Epoch 86/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3832
Epoch 87/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3843
Epoch 88/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3854
Epoch 89/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3770
Epoch 90/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3805
Epoch 91/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3859
Epoch 92/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3844
Epoch 93/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3744
Epoch 94/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3840
Epoch 95/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3833
Epoch 96/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3825
Epoch 97/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3824
Epoch 98/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3748
Epoch 99/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3770
Epoch 100/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3791
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
Matriz de confusión:
[[7733  230]
 [1336  701]]
Exactitud:  0.8434
Tasa de error:  0.1566
La correlación de los datos es:
           0         1         2         3
0  1.000000 -1.000000  0.472903 -0.494119
1 -1.000000  1.000000 -0.472903  0.494119
2  0.472903 -0.472903  1.000000 -0.805180
3 -0.494119  0.494119 -0.805180  1.000000

,CreditScore,Age,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,4.968409,-6.006786,0.542667,-1.991011,-0.325108,-0.181211,0.558768
1,-6.034883,5.661724,0.556614,4.225431,-0.921632,-0.262222,-0.148000

**Implementamos modelo de agrupamiento**

4. Se procede con la implementación del modelo

*Max Depth es el número de variables disponibles

*Gini es el criterio que indica el grado de error en el modelo

In [3]:
import numpy as np
import pandas as pd

#Para implementación del modelo
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

**Árbol de decisión**

In [98]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
# Ensure pydotplus is installed if you want to visualize the tree
!pip install pydotplus graphviz
from pydotplus import graph_from_dot_data
import pandas as pd # Make sure pandas is imported

# Reload the Churn_Modelling.csv data into a DataFrame
# This is necessary because XD and yd are now numpy arrays from the previous cell
nxl = '/content/Churn_Modelling.csv'
XDB_churn = pd.read_csv(nxl)

# Select the features (X) and the target (y)
# Exclude CustomerId as it's usually not a predictive feature
# Exclude Exited as it is the target variable
X_churn = XDB_churn[['CreditScore', 'Age', 'Balance',
                     'NumOfProducts', 'HasCrCard', 'IsActiveMember',
                     'EstimatedSalary']]
y_churn = XDB_churn['Exited'] # The target variable is already 0/1, no need to encode

# If there were categorical features in X_churn, you would encode them here
# For example, if 'Gender' was in X_churn:
# X_churn = pd.get_dummies(X_churn, columns=['Gender'], drop_first=True)

# Árbol de Clasificación (since Exited is binary)
# Using DecisionTreeClassifier is appropriate for binary classification
mar = DecisionTreeClassifier(max_depth=4)

# Fit the classifier
mar.fit(X_churn, y_churn) # Fit using the DataFrame X_churn and Series y_churn

# Visualización
# Get the feature names from the processed feature DataFrame
vs = X_churn.columns.tolist()

# Generate the dot data for the tree visualization
dot_data = export_graphviz(mar, feature_names=vs, filled=True,
                           class_names=['Not Exited', 'Exited']) # Add class names for clarity

# Create the graph from the dot data
graph = graph_from_dot_data(dot_data)

# Save the tree visualization to a PNG file
graph.write_png('Arbol_Exited.png')

print("Decision Tree visualization saved as Arbol_Exited.png")

Requirement already satisfied: pydotplus in /usr/local/lib/python3.11/dist-packages (2.0.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (0.20.3)
Requirement already satisfied: pyparsing>=2.0.1 in /usr/local/lib/python3.11/dist-packages (from pydotplus) (3.2.3)
Decision Tree visualization saved as Arbol_Exited.png